name: IncreasingItemDrops
main: com.crazymoosen.RunMobDrops
description: Item drops increase by 1 every time you mine a block, but you can turn it on and off with a command!
author: CrazyMoosen
api-version: 1.16
version: 4.0
commands:
  itemdrops:
    description: Turn increasing item drops on or off with this command!
    usage: /<command> [add | remove] [player]